version: "3.9"
services:
  db-postgres:
    image: postgres:16-alpine          # Banco PostgreSQL
    restart: unless-stopped
    ports:
      - "5432:5432"
    container_name: app_database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - dados_postgres:/var/lib/postgresql/data
    networks:
      - net_1
  app:
    build: 
      context: .
    ports: 
        - "3000:3000"
    environment:
        DB_HOST: db-postgres
        DB_PORT: 5432
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
    depends_on:
        - db-postgres
    networks:
      - net_1

volumes:
  dados_postgres:

networks:
  net_1:
    driver: bridge